#!/bin/zsh
resultDir="./classes/"

function preCompile {
	javac -classpath . -d $resultDir ./engine/ClassGenerator.java
	java  -classpath $resultDir engine.ClassGenerator
}

function compile {
	javac -classpath . -d $resultDir ./**/*.java
	java  -classpath $resultDir engine.Commander -ba $resultDir > /dev/null
}

function run {
	java -classpath $resultDir engine.Commander $*
}

preCompile
compile
run $*

